In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('C:/Users/DEV/Downloads/mobile phone price prediction.csv')

In [3]:
df

Unnamed: 0                                  Name  Rating  Spec_score  \
0              0                 Samsung Galaxy F14 5G    4.65          68   
1              1                    Samsung Galaxy A11    4.20          63   
2              2                    Samsung Galaxy A13    4.30          75   
3              3                    Samsung Galaxy F23    4.10          73   
4              4  Samsung Galaxy A03s (4GB RAM + 64GB)    4.10          69   
...          ...                                   ...     ...         ...   
1365        1365                               TCL 40R    4.05          75   
1366        1366                 TCL 50 XL NxtPaper 5G    4.10          80   
1367        1367                 TCL 50 XE NxtPaper 5G    4.00          80   
1368        1368                    TCL 40 NxtPaper 5G    4.50          79   
1369        1369                           TCL Trifold    4.65          93   

                                No_of_sim        Ram            Battery  \
0           Dual Sim, 3G, 4G, 5G, VoLTE,    4 GB RAM  6000 mAh Battery    
1               Dual Sim, 3G, 4G, VoLTE,    2 GB RAM  4000 mAh Battery    
2               Dual Sim, 3G, 4G, VoLTE,    4 GB RAM  5000 mAh Battery    
3               Dual Sim, 3G, 4G, VoLTE,    4 GB RAM   6000 mAh Battery   
4               Dual Sim, 3G, 4G, VoLTE,    4 GB RAM  5000 mAh Battery    
...                                   ...        ...                ...   
1365        Dual Sim, 3G, 4G, 5G, VoLTE,    4 GB RAM  5000 mAh Battery    
1366            Dual Sim, 3G, 4G, VoLTE,    8 GB RAM  5000 mAh Battery    
1367        Dual Sim, 3G, 4G, 5G, VoLTE,    6 GB RAM  5000 mAh Battery    
1368        Dual Sim, 3G, 4G, 5G, VoLTE,    6 GB RAM  5000 mAh Battery    
1369  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G,   12 GB RAM  4600 mAh Battery    

         Display                                             Camera  \
0     6.6 inches    50 MP + 2 MP Dual Rear &amp; 13 MP Front Camera   
1     6.4 inches  13 MP + 5 MP + 2 MP Triple Rear &amp; 8 MP Fro...   
2     6.6 inches            50 MP Quad Rear &amp; 8 MP Front Camera   
3     6.4 inches           48 MP Quad Rear &amp; 13 MP Front Camera   
4     6.5 inches  13 MP + 2 MP + 2 MP Triple Rear &amp; 5 MP Fro...   
...          ...                                                ...   
1365  6.6 inches  50 MP + 2 MP + 2 MP Triple Rear &amp; 8 MP Fro...   
1366  6.8 inches    50 MP + 2 MP Dual Rear &amp; 16 MP Front Camera   
1367  6.6 inches    50 MP + 2 MP Dual Rear &amp; 16 MP Front Camera   
1368  6.6 inches  50 MP + 2 MP + 2 MP Triple Rear &amp; 8 MP Fro...   
1369   10 inches                     Foldable Display, Dual Display   

                                        External_Memory Android_version  \
0                      Memory Card Supported, upto 1 TB              13   
1                    Memory Card Supported, upto 512 GB              10   
2                      Memory Card Supported, upto 1 TB              12   
3                      Memory Card Supported, upto 1 TB              12   
4                      Memory Card Supported, upto 1 TB              11   
...                                                 ...             ...   
1365                               Memory Card (Hybrid)              12   
1366                               Memory Card (Hybrid)              14   
1367                   Memory Card Supported, upto 1 TB              13   
1368                   Memory Card Supported, upto 1 TB              13   
1369  50 MP + 48 MP + 8 MP Triple Rear &amp; 32 MP F...              13   

         Price  company   Inbuilt_memory       fast_charging  \
0        9,999  Samsung   128 GB inbuilt   25W Fast Charging   
1        9,990  Samsung    32 GB inbuilt   15W Fast Charging   
2       11,999  Samsung    64 GB inbuilt   25W Fast Charging   
3       11,999  Samsung    64 GB inbuilt                 NaN   
4       11,999  Samsung    64 GB inbuilt   15W Fast Charging   
...        ...      ...       

# Basic Information About the Dataset

In [4]:
# Finding The Shape of The Dataset
df.shape

(1370, 18)

There are total 1370 rows and 18 Columns.

In [5]:
# Getting information about the basic columns in the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370 entries, 0 to 1369
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         1370 non-null   int64  
 1   Name               1370 non-null   object 
 2   Rating             1370 non-null   float64
 3   Spec_score         1370 non-null   int64  
 4   No_of_sim          1370 non-null   object 
 5   Ram                1370 non-null   object 
 6   Battery            1370 non-null   object 
 7   Display            1370 non-null   object 
 8   Camera             1370 non-null   object 
 9   External_Memory    1370 non-null   object 
 10  Android_version    927 non-null    object 
 11  Price              1370 non-null   object 
 12  company            1370 non-null   object 
 13  Inbuilt_memory     1351 non-null   object 
 14  fast_charging      1281 non-null   object 
 15  Screen_resolution  1368 non-null   object 
 16  Processor          1342 

In [6]:
# Let's check duplicate values
df.duplicated().sum()

0

## What are some of the problems based on info function

**1. Wrong Data types**

    Ram -> Int

    Battery -> Int

    Dispaly ->

    Camera ->

    Android_version -> Int

    Price -> Int

    Inbuilt Memory -> Int

**2. Missing Values Columns**

Android_version

Inbuilt_Memory

fast_charging

Screen_resolution

Processor

### Apply Unique function on Each column to identify what kind of values it holds

#### Name

In [7]:
df['Name'].nunique()

1334

#### Rating

In [8]:
df['Rating'].unique()

array([4.65, 4.2 , 4.3 , 4.1 , 4.4 , 4.05, 4.5 , 4.25, 4.75, 4.15, 4.35,
       4.45, 4.6 , 4.  , 4.55, 4.7 , 3.95, 3.75, 3.9 , 3.85])

#### Rating

In [9]:
df['Spec_score'].unique()

array([68, 63, 75, 73, 69, 76, 71, 85, 78, 72, 74, 79, 80, 62, 81, 82, 87,
       86, 88, 84, 83, 89, 91, 90, 96, 93, 92, 95, 65, 59, 42, 67, 60, 61,
       54, 66, 70, 51, 64, 53, 77, 94, 98, 97, 58, 57, 49, 46, 56, 55],
      dtype=int64)

#### No_of_sim

In [10]:
df['No_of_sim'].unique()

array(['Dual Sim, 3G, 4G, 5G, VoLTE, ', 'Dual Sim, 3G, 4G, VoLTE, ',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, ',
       'Single Sim, 3G, 4G, 5G, VoLTE, ', 'Dual Sim, 3G, 4G, ',
       'Single Sim, 3G, 4G, VoLTE, ', 'No Sim Supported, ',
       'Single Sim, 3G, 4G, 5G, VoLTE, Vo5G, ', 'Dual Sim, 3G, VoLTE, '],
      dtype=object)

#### RAM

In [11]:
df['Ram'].unique()

array(['4 GB RAM', '2 GB RAM', '6 GB RAM', '8 GB RAM', '12 GB RAM',
       '1 GB RAM', '3 GB RAM', '16 GB RAM', 'Helio G90T', '24 GB RAM',
       '18 GB RAM', '1.5 GB RAM', '128 GB inbuilt',
       '6000 mAh Battery with 22.5W Fast Charging', '256 GB inbuilt',
       '512 GB inbuilt'], dtype=object)

First check the occurences of '128 GB inbuilt',
       '6000 mAh Battery with 22.5W Fast Charging', '256 GB inbuilt',
       '512 GB inbuilt' and then decide whether to **drop** them or **replace** them

In [12]:
df['Ram'].value_counts()

8 GB RAM                                     528
4 GB RAM                                     253
12 GB RAM                                    246
6 GB RAM                                     214
16 GB RAM                                     41
3 GB RAM                                      38
2 GB RAM                                      22
256 GB inbuilt                                 8
128 GB inbuilt                                 7
18 GB RAM                                      4
512 GB inbuilt                                 3
24 GB RAM                                      2
1 GB RAM                                       1
Helio G90T                                     1
1.5 GB RAM                                     1
6000 mAh Battery with 22.5W Fast Charging      1
Name: Ram, dtype: int64

We drop the values **Helio G90T** & **6000 mAh Battery with 22.5W Fast Charging **

#### Battery

In [13]:
df['Battery'].unique()

array(['6000 mAh Battery ', '4000 mAh Battery ', '5000 mAh Battery ',
       '6000 mAh Battery', '3500 mAh Battery', '4500 mAh Battery ',
       '3400 mAh Battery ', '3300 mAh Battery ', '4050 mAh Battery ',
       '3900 mAh Battery ', '4300 mAh Battery ', '4800 mAh Battery ',
       '4200 mAh Battery ', '3700 mAh Battery ', '4400 mAh Battery ',
       '3500 mAh Battery ', '4320 mAh Battery ', '4030 mAh Battery',
       '1900 mAh Battery', '5000 mAh Battery', '2650 mAh Battery',
       '3000 mAh Battery', '4600 mAh Battery ', '4100 mAh Battery ',
       '5500 mAh Battery ', '4830 mAh Battery ', '4700 mAh Battery ',
       '4810 mAh Battery ', '5100 mAh Battery ', '5400 mAh Battery ',
       '4870 mAh Battery ', '5700 mAh Battery ', '4730 mAh Battery ',
       '5100 mAh Battery', '6 GB RAM, 64 GB inbuilt', '5200 mAh Battery ',
       '5240 mAh Battery ', '5050 mAh Battery ', '4310 mAh Battery ',
       '4350 mAh Battery ', '4880 mAh Battery ', '4520 mAh Battery ',
       '4260 mAh Batte

Strip the battery column.

**Different Values.**
    '6 GB RAM, 64 GB inbuilt'
    '6.75 inches, 720 x 1600 px Display '

In [14]:
df['Display'].unique()

array(['6.6 inches', '6.4 inches', '6.5 inches', '6.1 inches',
       '6.7 inches', '6.21 inches', '6.67 inches', '6.58 inches',
       '6.71 inches', '6.78 inches', '6.8 inches', '6.56 inches',
       '6.3 inches', '7.45 inches', '6.2 inches', '8.2 inches',
       '7.6 inches', '8 inches', '7.63 inches', '6.22 inches',
       '4.5 inches', '6.51 inches', '6.53 inches', '6.35 inches',
       '6.55 inches', '6.64 inches', '5.2 inches', '5.5 inches',
       '6.72 inches', '6.44 inches', '6.82 inches', '6.68 inches',
       '7 inches', '6.74 inches', '8.03 inches', '8.02 inches',
       '7.8 inches', '6.52 inches', '6.59 inches', '6.43 inches',
       '4300 mAh Battery with 30W Fast Charging', '6.62 inches',
       '6.57 inches', '6.73 inches', '6.83 inches', '7.1 inches',
       '7.4 inches', '7.56 inches', '7.82 inches', '6.38 inches',
       '6.79 inches', '6.61 inches', '6.69 inches', '12.1 inches',
       '6.77 inches', '6.75 inches', '6.81 inches', '7.2 inches',
       '7.71 inches'

**different values:**  '4300 mAh Battery with 30W Fast Charging', '48 MP + 5 MP + 2 MP Triple Rear &amp; 8 MP Front Camera'

In [15]:
df['External_Memory'].unique()

array(['Memory Card Supported, upto 1 TB',
       'Memory Card Supported, upto 512 GB', 'Memory Card Supported',
       'Memory Card (Hybrid), upto 1 TB', 'Memory Card Not Supported',
       'Memory Card (Hybrid)',
       '12 MP + 12 MP Dual Rear &amp; 10 MP Front Camera', 'Android v13',
       'Android v10', 'Android v12', 'Memory Card (Hybrid), upto 512 GB',
       '50 MP + 12 MP + 5 MP Triple Rear &amp; 10 MP + 4 MP Dual Front Camera',
       '200 MP Quad Rear &amp; 12 MP + 12 MP Dual Front Camera',
       '50 MP + 12 MP + 10 MP Triple Rear &amp; 10 MP + 4 MP Dual Front Camera',
       '50 MP + 12 MP + 10 MP Triple Rear &amp; 12 MP + 12 MP Dual Front Camera',
       'Memory Card Supported, upto 256 GB',
       'Memory Card Supported, upto 128 GB', 'Android v11', 'Android v15',
       'Android v14', '50 MP + 12 MP Dual Rear &amp; 32 MP Front Camera',
       '50 MP + 50 MP + 50 MP Triple Rear &amp; 32 MP + 32 MP Dual Front Camera',
       '200 MP + 12 MP + 12 MP Triple Rear &amp; 32 M

#### Android Version

In [16]:
df['Android_version'].unique()

array(['13', '10', '12', '11', '15', '10.0', '9.0 (Pie)', '14', nan,
       '7.1.1 (Nougat)', '8.0 (Oreo)', '8.1 (Oreo)', '5.1 (Lollipop)',
       '6.0 (Marshmallow)', '9 (Pie)', '3', '2', '4.0', '3.0 (Honeycomb)',
       '2.0', '3.0', '3.1', '5.0', '4.1'], dtype=object)

#### Price

In [17]:
df['Price'].unique()

array(['9,999', '9,990', '11,999', '11,990', '11,599', '12,298', '14,999',
       '14,990', '14,949', '19,999', '19,990', '19,799', '19,499',
       '18,999', '18,990', '20,999', '29,999', '28,990', '30,500',
       '30,999', '39,999', '39,990', '38,900', '37,999', '41,289',
       '41,790', '42,990', '42,999', '49,999', '49,990', '49,000',
       '47,990', '44,999', '44,990', '51,999', '54,990', '54,999',
       '59,999', '57,990', '64,999', '65,690', '69,990', '69,999',
       '70,000', '1,99,990', '1,84,999', '1,79,990', '1,77,999',
       '1,64,999', '1,59,999', '1,54,999', '1,39,999', '1,30,376',
       '1,29,999', '6,990', '6,999', '7,499', '7,999', '8,033', '8,199',
       '8,490', '9,499', '10,199', '10,499', '11,899', '11,580', '11,490',
       '11,390', '10,999', '12,350', '12,490', '15,050', '29,990',
       '29,799', '30,739', '31,398', '31,990', '38,990', '38,799',
       '37,990', '40,990', '49,940', '48,990', '46,990', '45,990',
       '45,210', '50,999', '56,990', '58,9

#### Company

In [18]:
df['company'].unique()

array(['Samsung', 'Vivo', 'Realme', 'OPPO', 'Oppo', 'iQOO', 'IQOO',
       'Poco', 'POCO', 'Honor', 'Nothing', 'Google', 'itel', 'Itel',
       'Asus', 'LG', 'Lenovo', 'Gionee', 'Motorola', 'OnePlus', 'Xiaomi',
       'Tecno', 'Huawei', 'Lava', 'Coolpad', 'TCL'], dtype=object)

#### Inbuilt Memory

In [19]:
df['Inbuilt_memory'].unique()

array([' 128 GB inbuilt', ' 32 GB inbuilt', ' 64 GB inbuilt',
       ' 256 GB inbuilt', ' 1 TB inbuilt', ' 512 GB inbuilt',
       ' 16 GB inbuilt', ' Octa Core', ' 258 GB inbuilt', ' 8 GB inbuilt',
       nan], dtype=object)

#### Fast Charging

In [20]:
df['fast_charging'].unique()

array([' 25W Fast Charging', ' 15W Fast Charging', nan,
       ' 18W Fast Charging', ' 30W Fast Charging', ' Fast Charging',
       ' 45W Fast Charging', ' 33W Fast Charging', ' 67W Fast Charging',
       ' 80W Fast Charging', ' 10W Fast Charging', ' 44W Fast Charging',
       ' 66W Fast Charging', ' 100W Fast Charging', ' 120W Fast Charging',
       ' 150W Fast Charging', ' 55W Fast Charging', ' 200W Fast Charging',
       ' 65W Fast Charging', ' 60W Fast Charging', ' 20W Fast Charging',
       ' 50W Fast Charging', ' 57W Fast Charging', ' 240W Fast Charging',
       ' 125W Fast Charging', ' 68W Fast Charging', ' 250W Fast Charging',
       ' 27W Fast Charging', ' 35W Fast Charging', ' 22.5W Fast Charging',
       ' 40W Fast Charging', ' 90W Fast Charging', ' 08W Fast Charging',
       ' 68.2W Fast Charging', ' 135W Fast Charging',
       ' 70W Fast Charging', ' Water Drop Notch', ' 88W Fast Charging',
       ' 7.5W Fast Charging'], dtype=object)

#### Screen Resolution

In [21]:
df['Screen_resolution'].unique()

array([' 2408 x 1080 px Display with Water Drop Notch',
       ' 720 x 1560 px Display with Punch Hole',
       ' 1080 x 2408 px Display with Water Drop Notch', ' 720 x 1600 px',
       ' 720 x 1600 px Display with Water Drop Notch',
       ' 1080 x 2340 px Display with Water Drop Notch',
       ' 720 x 1560 px Display with Water Drop Notch', ' 1080 x 2408 px',
       ' 1080 x 2400 px Display with Water Drop Notch', ' 1080 x 2340 px',
       ' 1080 x 2400 px', ' 720 x 1520 px Display with Water Drop Notch',
       ' 1080 x 2400 px Display with Punch Hole', ' 1440 x 3200 px',
       ' 1080 x 2340 px Display with Punch Hole', ' 1080 x 2640 px',
       ' 1080 x 2412 px', ' 1440 x 3040 px Display with Punch Hole',
       ' 1080 x 2400 px Display',
       ' 1080 x 2460 px Display with Punch Hole',
       ' 1440 x 3040 px Display', ' 1440 x 2960 px Display',
       ' 1812 x 2176 px', ' 1440 x 3120 px', ' 1440 x 3080 px',
       ' 720 x 1612 px', ' 480 x 854 px Display',
       ' 720 x 1544 p

#### Processor

In [22]:
df['Processor'].unique()

array([' Octa Core Processor', ' 1.8 GHz Processor', ' 2 GHz Processor',
       ' Octa Core', nan, ' Quad Core', ' Nine-Cores', ' Nine Core',
       ' Nine Cores', ' Deca Core Processor', ' 1.3 GHz Processor',
       ' 1.6 GHz Processor', ' 2.3 GHz Processor', ' Deca Core',
       ' 128 GB inbuilt'], dtype=object)

#### Processor Name

In [23]:
df['Processor_name'].unique()

array(['Exynos 1330', 'Octa Core', 'Helio G88', 'Helio P35',
       'Dimensity 700', 'Exynos 9611', 'Exynos  850', 'Exynos 1280',
       'Snapdragon 695', 'Exynos 850', 'Helio P65', 'Octa Core Processor',
       'Snapdragon 680', 'Helio G80', 'Samsung Exynos 7884',
       'Dimensity 6100 Plus', 'Dimensity 700 5G', 'Snapdragon  680',
       'Snapdragon 888', 'Exynos 1380', 'Snapdragon 865', 'Exynos 980',
       'Snapdragon 730', 'Snapdragon 675', 'Snapdragon 7 Gen1',
       'Snapdragon 750G', 'Snapdragon 855+', 'Snapdragon 870',
       'Snapdragon 710', 'Exynos 1480', 'Snapdragon  720G ',
       'Snapdragon 778g', 'Exynos 2200', 'Snapdragon 7+ Gen2',
       'Snapdragon 8 Gen 2', 'Exynos 9825', 'Snapdragon 7s Gen2',
       'Exynos 2100', 'Dimensity 1300', 'Snapdragon 778G+',
       'Snapdragon 778G', 'Exynos 2300', 'Snapdragon 8+ Gen1',
       'Snapdragon 8 Gen3', 'Snapdragon  8+ Gen1', 'Snapdragon  8 Gen1',
       'Exynos 990', 'Snapdragon 855', 'Exynos 8895', 'Exynos  2100',
       'Ex

# EDA and Data Cleaning

In [24]:
def strip(dataframe, col):
    dataframe[col] = dataframe[col].str.strip()

In [25]:
strip(df,'Battery')

In [26]:
strip(df,'No_of_sim')

In [27]:
strip(df,'Inbuilt_memory')

In [28]:
strip(df,'fast_charging')

In [29]:
strip(df,'Screen_resolution')

In [30]:
strip(df,'Processor')

In [31]:
strip(df,'Processor_name')

In [32]:
strip(df,'Display')

## RAM column

We remove the values 'Helio G90T','6000 mAh Battery with 22.5W Fast Charging'.
also wherever we have null values for inbuilt memory we fill those using the corresponding row values of RAM.

In [33]:
df = df[(df['Ram'] !='Helio G90T')]

In [34]:
df = df[(df['Ram'] !='6000 mAh Battery with 22.5W Fast Charging')]

In [35]:
count = 0
for index,row in df.iterrows():
    if pd.isnull(row['Inbuilt_memory']):
        df.at[index, 'Inbuilt_memory'] = row['Ram']
        df.at[index, 'Ram'] ='0 GB RAM'

In [39]:
df['Ram'].unique()

array(['4 GB RAM', '2 GB RAM', '6 GB RAM', '8 GB RAM', '12 GB RAM',
       '1 GB RAM', '3 GB RAM', '16 GB RAM', '24 GB RAM', '18 GB RAM',
       '1.5 GB RAM', '0 GB RAM'], dtype=object)

# Fold and Dual Display

We create new column called fold and dual display. it contains information whether a phone has foldable or dual or both display.

In [50]:
df['Fold_and_dual_dis'] = ''

In [51]:
l = ['Foldable Display, Dual Display','Dual Display','Foldable Display']
for index,row in df.iterrows():
    if row['Camera'] in l:
        df.at[index,'Fold_and_dual_dis'] = row['Camera']
        df.at[index,'Camera'] = row['External_Memory']
        df.at[index, 'External_Memory'] = ''

In [52]:
df['Fold_and_dual_dis'].unique()

array(['', 'Foldable Display, Dual Display', 'Dual Display',
       'Foldable Display'], dtype=object)

In [53]:
df = df[df['Unnamed: 0'] != '']

# External Memory

Now wherever and cell in external memory startswith android then we fill the corresponding cell in android version with it.

In [54]:
count = 0
for index, row in df.iterrows():
    if row['External_Memory'].startswith('Android'):
        df.at[index, 'Android_version'] = row['External_Memory']

# Android Version

In [55]:
df['Android_version'].isna().sum()       

72

In [56]:
count = 0
for index, row in df.iterrows():
    if row['External_Memory'].startswith('Harmony'):
        df.at[index, 'Android_version'] = row['External_Memory']

In [57]:
count = 0
for index, row in df.iterrows():
    if row['External_Memory'].startswith('EMUI'):
        df.at[index, 'Android_version'] = row['External_Memory']

In [58]:
android_dict = {'Android v13':'13','10.0':'10','Android v10':10,'9.0 (Pie)':9,'Android v12':12,'7.1.1 (Nougat)':'7','8.0 (Oreo)':8,
               '8.1 (Oreo)':'8','5.1 (Lollipop)':'5','6.0 (Marshmallow)':'6','Android v11':'11','Android v15':'15',
               'Android v14':'14','Android v9.0 (Pie)':'9',"9 (Pie)":'9',"Android v12.1":'12','4.0':'4','3.0':'3','3.1':'3','5.0':'5',
               '2.0':'2','Android v10.0':'10',"3.0 (Honeycomb)":'3','HarmonyOS v4':'4','EMUI v14':'14','HarmonyOS v3.0':3,
               'HarmonyOS':'1','HarmonyOS v4.0':'4','HarmonyOS v5.0':'5','HarmonyOS v2.0':'2','HarmonyOS v4.2':'4','HarmonyOS v5':'5',
               '4.1':4,8:'8',9:'9',3:'3',4:'4',10:'10',12:'12',4:'4'}

In [59]:
df['Android_version'] = df['Android_version'].replace(android_dict)

In [60]:
df['Android_version'].unique()

array(['13', '10', '12', '11', '15', 9, '14', nan, 10, 12, '7', 8, '8',
       '5', '6', '9', '3', '2', '4', 'Android', 3, '1', 4], dtype=object)

In [61]:
df = df[df['Android_version'] != 'Android']

# Company Column

In [62]:
company_dict = {'OPPO':'Oppo','iQOO':'IQOO','POCO':'Poco','itel':'Itel'}

In [63]:
df['company'] = df['company'].replace(company_dict)

# Fast Charging

In [64]:
df['fast_charging'] = df['fast_charging'].fillna('0')

# Processor

In [65]:
processor_l = ['1.8 GHz Processor', '2 GHz Processor', '1.3 GHz Processor', '1.6 GHz Processor','2.3 GHz Processor']
fil_rows = []
count = 0
for index,row in df.iterrows():
    if row['Processor'] in processor_l:
        df.at[index,'Processor'] = 'Octa Core'

In [66]:
processor_dict = {'Octa Core Processor':'Octa Core','Nine-Cores':'Nine Core','Nine Cores':'Nine Core','Deca Core Processor':'Deca Core'}

In [67]:
df['Processor'] = df['Processor'].replace(processor_dict)

In [68]:
df['Processor'].unique()

array(['Octa Core', nan, 'Quad Core', 'Nine Core', 'Deca Core'],
      dtype=object)

# Processor Name

In [69]:
for index,row in df.iterrows():
    if row['Processor_name'] == 'Octa Core':
        df.at[index,'Processor_name'] = ''

In [70]:
for i in df.columns:
    count = 0
    for index, row in df.iterrows():
        if row[i] == '':
            count += 1
    print(i, ': ' ,count)

Unnamed: 0 :  0
Name :  0
Rating :  0
Spec_score :  0
No_of_sim :  0
Ram :  0
Battery :  0
Display :  0
Camera :  0
External_Memory :  78
Android_version :  0
Price :  0
company :  0
Inbuilt_memory :  0
fast_charging :  0
Screen_resolution :  0
Processor :  0
Processor_name :  7
Fold_and_dual_dis :  1289


# External Memory

In [71]:
for index, row in df.iterrows():
    if row['External_Memory'] == '':
        df.at[index,'External_Memory'] = 'No'

In [72]:
li = ['Android v13', 'Android v10','Android v12','Android v11', 'Android v15','Android v14','Android v9.0 (Pie)','Android v10.0',
       'Android v12.1', 'No FM Radio','HarmonyOS v4', 'EMUI v14',
       'HarmonyOS v3.0', 'HarmonyOS', 'HarmonyOS v4.0', 'HarmonyOS v5.0',
       'HarmonyOS v2.0', 'HarmonyOS v4.2', 'HarmonyOS v5']

In [73]:
for index, row in df.iterrows():
    if row['External_Memory'] in li:
        df.at[index,'External_Memory'] = ''

In [74]:
for index, row in df.iterrows():
    if row['External_Memory'] =='':
        df.at[index,'External_Memory'] = 'No'

# Filling Null Values

In [75]:
for index, row in df.iterrows():
    if row['Processor_name'] =='':
        df.at[index,'Processor_name'] = 'Snapdragon 8+ Gen1'

In [76]:
for index, row in df.iterrows():
    if pd.isnull(row['Processor']):
        df.at[index,'Processor'] = 'Octa Core'

In [77]:
df['Android_version'] = df['Android_version'].fillna('13')

In [78]:
for index,row in df.iterrows():
    if row['Fold_and_dual_dis'] == '':
        df.at[index,'Fold_and_dual_dis'] = 'None'

In [79]:
df.isna().sum()

Unnamed: 0           0
Name                 0
Rating               0
Spec_score           0
No_of_sim            0
Ram                  0
Battery              0
Display              0
Camera               0
External_Memory      0
Android_version      0
Price                0
company              0
Inbuilt_memory       0
fast_charging        0
Screen_resolution    0
Processor            0
Processor_name       0
Fold_and_dual_dis    0
dtype: int64

## Splitting the column

In [80]:
def split_col(dataframe,col,split_on,get_index):
    dataframe[col] = dataframe[col].str.split(split_on).str.get(get_index)

In [81]:
split_col(df,'Ram',' ',0)

AttributeError: Can only use .str accessor with string values!

In [82]:
df['Ram'].unique()

array([ 4. ,  2. ,  6. ,  8. , 12. ,  1. ,  3. , 16. , 24. , 18. ,  1.5,
        0. ])

In [83]:
split_col(df,'Battery',' ',0)

In [84]:
df['Battery'].unique()

array(['6000', '4000', '5000', '3500', '4500', '3400', '3300', '4050',
       '3900', '4300', '4800', '4200', '3700', '4400', '4320', '4030',
       '1900', '2650', '3000', '4600', '4100', '5500', '4830', '4700',
       '4810', '5100', '5400', '4870', '5700', '4730', '5200', '5240',
       '5050', '4310', '4350', '4880', '4520', '4260', '4820', '4805',
       '5160', '5080', '5065', '10500', '5800', '5300', '5450', '5600',
       '2800', '4620', '4385', '4410', '4355', '4492', '4575', '5003',
       '4821', '7000', '3760', '2600', '4900', '4020', '4450', '4610',
       '3800', '3440', '2510', '6100', '2100', '5020', '4980', '4250',
       '4460', '4815', '4750', '5330', '5010'], dtype=object)

In [85]:
split_col(df, 'Display',' ',0)

In [86]:
df['Display'].unique()

array(['6.6', '6.4', '6.5', '6.1', '6.7', '6.21', '6.67', '6.58', '6.71',
       '6.78', '6.8', '6.56', '6.3', '7.45', '6.2', '8.2', '7.6', '8',
       '7.63', '6.22', '4.5', '6.51', '6.53', '6.35', '6.55', '6.64',
       '5.2', '5.5', '6.72', '6.44', '6.82', '6.68', '7', '6.74', '8.03',
       '8.02', '7.8', '6.52', '6.59', '6.43', '6.62', '6.57', '6.73',
       '6.83', '7.1', '7.4', '7.56', '7.82', '6.38', '6.79', '6.61',
       '6.69', '12.1', '6.77', '6.75', '6.81', '7.2', '7.71', '7.92',
       '6.76', '7.9', '5.6', '5.7', '6.34', '6.14', '6.03', '8.3', '5.9',
       '5.92', '6', '6.26', '6.09', '5.99', '6.92', '5', '6.45', '6.9',
       '6.47', '6.28', '6.49', '6.08', '7.85', '7.11', '6.95', '6.94',
       '7.09', '10'], dtype=object)

In [87]:
split_col(df,'Inbuilt_memory',' ',0)

In [88]:
df['Inbuilt_memory'].unique()

array(['128', '32', '64', '256', '1', '512', '16', '258', '8'],
      dtype=object)

In [89]:
split_col(df,'fast_charging',' ',0)

In [90]:
df['fast_charging'].unique()

array(['25W', '15W', '0', '18W', '30W', 'Fast', '45W', '33W', '67W',
       '80W', '10W', '44W', '66W', '100W', '120W', '150W', '55W', '200W',
       '65W', '60W', '20W', '50W', '57W', '240W', '125W', '68W', '250W',
       '27W', '35W', '22.5W', '40W', '90W', '08W', '68.2W', '135W', '70W',
       '88W', '7.5W'], dtype=object)

In [91]:
df = df[df['fast_charging'] != 'Fast']

In [92]:
def replace_fun(dataframe,col,replace_val,replace_with):
    dataframe[col] = dataframe[col].str.replace(replace_val, replace_with)

In [93]:
replace_fun(df,'Price',',','')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [94]:
replace_fun(df,'fast_charging','W','')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


# Changing Datatypes

In [95]:
def change_dtypes(dataframe,col,dtypes):
    dataframe[col] = dataframe[col].astype(dtypes)

In [96]:
change_dtypes(df,'Ram','float')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [97]:
change_dtypes(df,'Battery','int32')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [98]:
change_dtypes(df,'Display','float')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [99]:
change_dtypes(df,'fast_charging','float')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [100]:
change_dtypes(df,'Inbuilt_memory','int32')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [101]:
change_dtypes(df,'Android_version','float')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [102]:
change_dtypes(df,'Price','int64')

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


# Feature Creation

In [103]:
df['hresolution'] = df['Screen_resolution'].str.split(' ').str.get(0)

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [104]:
df['vresolution'] = df['Screen_resolution'].str.split(' ').str.get(2)

c:\users\dev\appdata\local\programs\python\python379\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [105]:
df = df[df['hresolution'] != 'Full']

In [106]:
change_dtypes(df,'hresolution','int64')

In [107]:
change_dtypes(df,'vresolution','int64')

In [108]:
df['External_Memory'].unique()

array(['Memory Card Supported, upto 1 TB',
       'Memory Card Supported, upto 512 GB', 'Memory Card Supported',
       'Memory Card (Hybrid), upto 1 TB', 'Memory Card Not Supported',
       'Memory Card (Hybrid)', 'No', 'Memory Card Supported, upto 256 GB',
       'Memory Card Supported, upto 128 GB',
       'Memory Card Supported, upto 2 TB',
       'Memory Card (Hybrid), upto 2 TB',
       'Memory Card (Hybrid), upto 512 GB',
       'Memory Card (Hybrid), upto 256 GB',
       'Memory Card Supported, upto 32 GB'], dtype=object)

In [109]:
for index,row in df.iterrows():
    if (' ').join(row['External_Memory'].split(' ')[0:3]) == 'Memory Card Supported,':
        if row['External_Memory'].split(' ')[4] == '1':
            df.at[index,'External_memory'] = 1024
        else:
            df.at[index,'External_memory'] = row['External_Memory'].split(' ')[4]
    elif (' ').join(row['External_Memory'].split(' ')[0:3]) == 'Memory Card Supported':
        df.at[index,'External_memory'] = 128
    elif (' ').join(row['External_Memory'].split(' ')[0:3]) == 'Memory Card (Hybrid),':
        df.at[index,'External_memory'] = row['External_Memory'].split(' ')[4]
    elif (' ').join(row['External_Memory'].split(' ')[0:3]) == 'Memory Card (Hybrid)':
        df.at[index,'External_memory'] = 128
    elif (' ').join(row['External_Memory'].split(' ')[0:4]) == 'Memory Card Not Supported':
        df.at[index,'External_memory'] = 0
    elif row['External_Memory'] == 'No':
        df.at[index,'External_memory'] = 0    

In [110]:
processor = {'Quad Core':1,'Octa Core':2,'Nine Core':3,'Deca Core':4}

In [111]:
df['Processor'] = df['Processor'].replace(processor)

In [112]:
df['Fold_and_dual_dis'].unique()

array(['None', 'Foldable Display, Dual Display', 'Dual Display',
       'Foldable Display'], dtype=object)

In [113]:
fold_and_dual_dis = {'None':0,'Dual Display':1,'Foldable Display':2,'Foldable Display, Dual Display':3}

In [114]:
df['Fold_and_dual_dis'] = df['Fold_and_dual_dis'].replace(fold_and_dual_dis)

In [115]:
processor_name = {'Sanpdragon':'Snapdragon','Qualcomm':'Snapdragon','Samsung':'Exynos','Google':'Tensor','Quad':'Snapdragon','Octa':'Snapdragon','SC9863A':'Snapdragon'}

In [116]:
df['Processor_name'] = df['Processor_name'].str.split(' ').str.get(0)

In [117]:
df['Processor_name'] = df['Processor_name'].replace(processor_name)

In [118]:
pro_name ={'Snapdragon':1,'Dimensity':2,'Helio':3,'Exynos':4,'Unisoc':5,'Kirin':6,'Tiger':7,'Tensor':8}

In [119]:
df['Processor_name'] = df['Processor_name'].replace(pro_name)

In [120]:
company_name = {'Vivo':1,'Realme':2,'Samsung':3,'Motorola':4,'Poco':5,'Xiaomi':6,'Honor':7,'OnePlus':8,'Oppo':9,'Huawei':10,
               'IQOO':11,'TCL':12,'Asus':13,'Lava':14,'Google':15,'Itel':16,'Nothing':17,'Lenovo':18,'Tecno':19,'Gionee':20,
               'LG':21,'Coolpad':22}

In [121]:
df['company'] = df['company'].replace(company_name)

In [122]:
df

Unnamed: 0                                  Name  Rating  Spec_score  \
0              0                 Samsung Galaxy F14 5G    4.65          68   
1              1                    Samsung Galaxy A11    4.20          63   
2              2                    Samsung Galaxy A13    4.30          75   
3              3                    Samsung Galaxy F23    4.10          73   
4              4  Samsung Galaxy A03s (4GB RAM + 64GB)    4.10          69   
...          ...                                   ...     ...         ...   
1365        1365                               TCL 40R    4.05          75   
1366        1366                 TCL 50 XL NxtPaper 5G    4.10          80   
1367        1367                 TCL 50 XE NxtPaper 5G    4.00          80   
1368        1368                    TCL 40 NxtPaper 5G    4.50          79   
1369        1369                           TCL Trifold    4.65          93   

                               No_of_sim   Ram  Battery  Display  \
0           Dual Sim, 3G, 4G, 5G, VoLTE,   4.0     6000      6.6   
1               Dual Sim, 3G, 4G, VoLTE,   2.0     4000      6.4   
2               Dual Sim, 3G, 4G, VoLTE,   4.0     5000      6.6   
3               Dual Sim, 3G, 4G, VoLTE,   4.0     6000      6.4   
4               Dual Sim, 3G, 4G, VoLTE,   4.0     5000      6.5   
...                                  ...   ...      ...      ...   
1365        Dual Sim, 3G, 4G, 5G, VoLTE,   4.0     5000      6.6   
1366            Dual Sim, 3G, 4G, VoLTE,   8.0     5000      6.8   
1367        Dual Sim, 3G, 4G, 5G, VoLTE,   6.0     5000      6.6   
1368        Dual Sim, 3G, 4G, 5G, VoLTE,   6.0     5000      6.6   
1369  Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G,  12.0     4600     10.0   

                                                 Camera  \
0       50 MP + 2 MP Dual Rear &amp; 13 MP Front Camera   
1     13 MP + 5 MP + 2 MP Triple Rear &amp; 8 MP Fro...   
2               50 MP Quad Rear &amp; 8 MP Front Camera   
3              48 MP Quad Rear &amp; 13 MP Front Camera   
4     13 MP + 2 MP + 2 MP Triple Rear &amp; 5 MP Fro...   
...                                                 ...   
1365  50 MP + 2 MP + 2 MP Triple Rear &amp; 8 MP Fro...   
1366    50 MP + 2 MP Dual Rear &amp; 16 MP Front Camera   
1367    50 MP + 2 MP Dual Rear &amp; 16 MP Front Camera   
1368  50 MP + 2 MP + 2 MP Triple Rear &amp; 8 MP Fro...   
1369  50 MP + 48 MP + 8 MP Triple Rear &amp; 32 MP F...   

                         External_Memory  ...  company  Inbuilt_memory  \
0       Memory Card Supported, upto 1 TB  ...        3             128   
1     Memory Card Supported, upto 512 GB  ...        3              32   
2       Memory Card Supported, upto 1 TB  ...        3              64   
3       Memory Card Supported, upto 1 TB  ...        3              64   
4       Memory Card Supported, upto 1 TB  ...        3              64   
...                                  ...  ...      ...             ...   
1365                Memory Card (Hybrid)  ...       12              64   
1366                Memory Card (Hybrid)  ...       12             128   
1367    Memory Card Supported, upto 1 TB  ...       12             256   
1368    Memory Card Supported, upto 1 TB  ...       12             256   
1369                                  No  ...       12             256   

      fast_charging                             Screen_resolution  Processor  \
0              25.0  2408 x 1080 px Display with Water Drop Notch          2   
1              15.0         720 x 1560 px Display with Punch Hole          2   
2              25.0  1080 x 2408 px Display with Water Drop Notch          2   
3               0.0                                 720 x 1600 px          2   
4              15.0   720 x 1600 px Display with Water Drop Notch          2   
...             ...                                           ...        ...   
1365           15.0                                 720 x 1612 px          2   
1366          